#!/bin/bash

for SRC in *.c
do
    for LIB in c jemalloc mimalloc tcmalloc
    do
        for OPT in O0 O2 O3
        do
            gcc -g -pie -fpie -${OPT} ${SRC} -l${LIB} -o $(basename ${SRC} .c).${LIB}.${OPT}.executable
        done
    done
done
