#!/bin/bash

for LIB in c jemalloc tcmalloc
do
    gcc -O main.common.c -l${LIB} -o main.${LIB}.executable
done

gcc -O main.alloca.c -o main.alloca.executable
gcc -O main.mimalloc.c -lmimalloc -o main.mimalloc.executable
